# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[en]
  languageCode = "en-us"
  contentDir = "content/en"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.

# Uncomment the lines below to configure your website in a second language.
[eu]
  languageCode = "eu"
  contentDir = "content/eu"
  
[[eu.menu.main]]
  name = "Taldekideak"
  url = "people"
  weight = 1


[[eu.menu.main]]
  name = "Proiektuak"
  url = "project/#projects"
  weight = 2

[[eu.menu.main]]
  name = "Publikazioak"
  url = "publication/#publications"
  weight = 4
  
[[eu.menu.main]]
  name = "Ikerketa-lerroak"
  url = "research/research"
  weight = 3
  
[[eu.menu.main]]
  name = "Irakaskuntza"
  url = "teaching"
  weight = 5
  
 [[eu.menu.main]]
  name = "Argazki-bilduma"
  url = "gallery/#gallery"
  weight = 6 
  
  
[es]
  languageCode = "es"
  contentDir = "content/es"
  
[[es.menu.main]]
  name = "El grupo"
  url = "people"
  weight = 1


[[es.menu.main]]
  name = "Proyectos"
  url = "project/#projects"
  weight = 2

[[es.menu.main]]
  name = "Publicaciones"
  url = "publication/#publications"
  weight = 4
  
[[es.menu.main]]
  name = "Líneas de investigación"
  url = "research/research"
  weight = 3
  
[[es.menu.main]]
  name = "Docencia"
  url = "teaching"
  weight = 5
 
[[es.menu.main]]
  name = "Galería"
  url = "gallery/#gallery"
  weight = 6
 
#[zh]
#  languageCode = "zh-Hans"
#  contentDir = "content/zh"
#  title = "Chinese website title..."
#  [zh.params]
#    description = "Site description in Chinese..."
#  [[zh.menu.main]]
#    name = "Wo"
#    url = "#about"
#    weight = 1
